CFLAGS=-Wall -g

all: \
cliente4 \
servidor4 \
 

cliente4: cliente4.c
	gcc $(CFLAGS) -o $@ cliente4.c


servidor4: servidor4.c
	gcc $(CFLAGS) -o $@ servidor4.c

clean: 
	rm -f *.o servidor4 cliente4 


